// Turn the prelude and node-shim modules in this directory into a C header
// (skein-prelude.h) that patches/quickjs.patch compiles into qjs. Run by
// scripts/build-toolset.sh: node toolset/tools/qjs/gen-prelude.mjs <out.h>
import { readFileSync, writeFileSync } from "node:fs";

const dir = new URL("./", import.meta.url);
const src = (f) => readFileSync(new URL(f, dir), "utf8");

// [module name, file]: evaluated in this order, before the user's script.
const always = [["skein:prelude", "prelude.js"]];
const node = [
  ["skein:node", "node.js"],
  ["fs", "modules/fs.js"], ["node:fs", "modules/fs.js"],
  ["fs/promises", "modules/fs-promises.js"], ["node:fs/promises", "modules/fs-promises.js"],
  ["path", "modules/path.js"], ["node:path", "modules/path.js"],
  ["process", "modules/process.js"], ["node:process", "modules/process.js"],
  ["buffer", "modules/buffer.js"], ["node:buffer", "modules/buffer.js"],
];

// JSON string escapes are valid C for this ASCII-only source; `?` is escaped so `??=` is never a trigraph.
const cstr = (s) => JSON.stringify(s).replace(/\?/g, "\\?");
for (const [, f] of [...always, ...node]) if (/[^\x00-\x7f]/.test(src(f))) throw new Error(`${f}: keep the prelude ASCII`);
const table = (name, list) =>
  `static const struct { const char *name; const char *src; } ${name}[] = {\n` +
  list.map(([n, f]) => `    { ${cstr(n)}, ${cstr(src(f))} },\n`).join("") + "};\n";

writeFileSync(process.argv[2], "/* generated by toolset/tools/qjs/gen-prelude.mjs: do not edit */\n" +
  table("skein_prelude", always) + table("skein_node_modules", node));
